# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAuthApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAuthApp
  pod 'SwiftKeychainWrapper', '~> 3.0'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'SwiftAuthAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
